# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Ben Whitehead
tagline:	'Developer'
description:'I am a web develpper in Portland, Oregon. I attend school at Lewis & Clark College'
url:		http://bwhthd.com

author:
  name:	'Ben Whitehead'
  url:	http://bwhthd.com

paginate:	6

# Custom vars
icon: /assets/images/icon.png
cover: /assets/images/Log.jpg
resume: /resBen.pdf
version:	1.0.0
github:
  repo:	https://github.com/camporez/camporez.github.io
copyright: <p class="copyright">&copy;
